version: '3.8'
services:
  db:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=leanco
      - POSTGRES_PASSWORD=leanco
      - POSTGRES_DB=leanco
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local